### ISSUE TITLE
Error when trying to start spa in SSR mode

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#2622]
✗ yarn start:ssr
yarn run v1.16.0
$ node dist/ssr/server
Node server listening on http://localhost:4200

When I try to access it, I get this:

TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (/Users/i867028/git/github/spartacus/dist/ssr/server.js:32456:15)
    at subscribeToResult (/Users/i867028/git/github/spartacus/dist/ssr/server.js:32355:76)
    at CatchSubscriber.error (/Users/i867028/git/github/spartacus/dist/ssr/server.js:35205:94)
    at SwitchMapSubscriber.OuterSubscriber.notifyError (/Users/i867028/git/github/spartacus/dist/ssr/server.js:32325:26)
    at InnerSubscriber._error (/Users/i867028/git/github/spartacus/dist/ssr/server.js:32386:21)
    at InnerSubscriber.Subscriber.error (/Users/i867028/git/github/spartacus/dist/ssr/server.js:29247:18)
    at CatchSubscriber.OuterSubscriber.notifyError (/Users/i867028/git/github/spartacus/dist/ssr/server.js:32325:26)
    at InnerSubscriber._error (/Users/i867028/git/github/spartacus/dist/ssr/server.js:32386:21)
    at InnerSubscriber.Subscriber.error (/Users/i867028/git/github/spartacus/dist/ssr/server.js:29247:18)
    at Observable._subscribe (/Users/i867028/git/github/spartacus/dist/ssr/server.js:31333:117)

**Comment by Xymmer** [comment]
Gil creates ssr server and tries to repro

**Comment by hackergil** [comment]
This was happening because the production backend endpoint wasn't properly configured. I've created a small document for SSR setup (PR above)
