### ISSUE TITLE
Product Carousel doesn't render in SSR

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#3215]
Opening home page in SSR gives this error in ssr console:
```
ERROR TypeError: Invalid event target
    at setupSubscription (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:37460:15)
    at Observable._subscribe (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:37434:9)
    at Observable._trySubscribe (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:33398:25)
    at Observable.subscribe (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:33384:22)
    at MapOperator.call (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:36328:23)
    at Observable.subscribe (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:33379:31)
    at subscribeToResult (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:36658:23)
    at MergeMapSubscriber._innerSub (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:37033:90)
    at MergeMapSubscriber._tryNext (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:37027:14)
    at MergeMapSubscriber._next (C:\divante\bugs\ssr-beta1\dist\ssr\server.js:37010:18)
```

**Comment by znikola** [comment]
To QA: run the app in ssr mode and open the homepage. You should carousel with three products.

**Comment by KateChuen** [comment]
tested locally. I see the product carousel, no error
<img width="1435" alt="Screen Shot 2019-06-25 at 4 04 39 PM" src="https://user-images.githubusercontent.com/45409515/60182513-6f7f3c00-97f2-11e9-83dc-2160d3fb6a59.png">

**Comment by KateChuen** [comment]
As Nik pointed out to me, it was still registering service worker, so I had to disable javascript. 

New screenshot: 
![Screen Shot 2019-06-26 at 9 28 02 AM](https://user-images.githubusercontent.com/45409515/60183745-df8ec180-97f4-11e9-93e5-0edeb7bba75c.png)
