### ISSUE TITLE
Fix: mobile/register-mobile.e2e-spec.ts

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4039]
mobile/register-mobile.e2e-spec.ts failed on the last 3 Jenkins runs.

This is the [logs](https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/314/console):
CypressError: Timed out retrying: cy.click() failed because this element is not visible:

<a role="link" href="/electronics-spa/en/USD/login">Sign In...</a>

This element '<a>' is not visible because it has an effective width and height of: '0 x 0' pixels.

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:4200/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:4200/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:4200/__cypress/runner/cypress_runner.js:65275:17)
      at Object.retry (http://localhost:4200/__cypress/runner/cypress_runner.js:58816:16)
      at retryActionability (http://localhost:4200/__cypress/runner/cypress_runner.js:50595:19)
      at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:127195:23)
      at Function.Promise.attempt.Promise.try (http://localhost:4200/__cypress/runner/cypress_runner.js:124569:29)
      at tryFn (http://localhost:4200/__cypress/runner/cypress_runner.js:59052:24)
      at whenStable (http://localhost:4200/__cypress/runner/cypress_runner.js:59080:12)
      at http://localhost:4200/__cypress/runner/cypress_runner.js:58840:16
      at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:125394:18)
      at Promise._fulfill (http://localhost:4200/__cypress/runner/cypress_runner.js:125339:18)

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4111
