### ISSUE TITLE
Payment methods e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6152]
mobile/my-account/payment-methods-mobile.e2e-spec.ts
regression/my-account/payment-methods.e2e-spec.ts

This test has been consistently failing on dev-17 as well. Potentially use this opportunity to fix it for good. 

As usual, it cannot find the element with id #deliveryMode-standard-gross, but also has other issues. Console says it is unable to find the text with _**Set As Default**_ and _**Delete**_

Maybe duplicate issue with GH-5867?

**Comment by psmul** [comment]
QA steps:
- run tests in payment-methods.e2e-spec.ts and mobile/payment-methods.e2e-spec.ts

Expected result:
- tests should pass

**Comment by plabadie** [comment]
Failing on the 1.5.x branch

**Comment by hackergil** [comment]
The URL above is pointing to an old build for the develop branch. Tests are passing now in 1.5.x branch.

**Comment by plabadie** [comment]
Still fails in 1.5
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/22/consoleText

**Comment by reyhanehsalkhi** [comment]
the test has probably failed on pipeline because of xhr call to get the order review information gets timeout.

**Comment by reyhanehsalkhi** [comment]
After multiple runs of the test was able to reproduce locally. 
The error is 
"Unable to find an element with the text: Set as default. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible."

We need to use a more specific matcher. 

`cy.getByText('Add New Payment').click({ force: true });
`
it should be 

```
cy.get('.cx-checkout-btns')
    .getByText('Add New Payment')
    .click({ force: true });
```

same if true about the delete button.

**Comment by reyhanehsalkhi** [comment]
The problem was not reproducible locally through UI. But could reproduce it using this command 
or i in {1..40}; do yarn e2e:cy:run --spec cypress/integration/mobile/my-account/payment-methods-mobile.e2e-spec.ts; done

The test only fails four times. 


  1) 576p resolution - Payment Methods Authenticated user should add a second payment method:
     CypressError: Timed out retrying: Expected to find element: 'cx-review-submit', but never found it.
      at Object.cypressErr (http://localhost:4200/__cypress/runner/cypress_runner.js:85348:11)
      at Object.throwErr (http://localhost:4200/__cypress/runner/cypress_runner.js:85303:18)
      at Object.throwErrByPath (http://localhost:4200/__cypress/runner/cypress_runner.js:85335:17)
      at retry (http://localhost:4200/__cypress/runner/cypress_runner.js:77321:16)
      at onFailFn (http://localhost:4200/__cypress/runner/cypress_runner.js:68422:16)
      at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:117000:10)
      at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:117075:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:4200/__cypress/runner/cypress_runner.js:113687:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>

  2) 576p resolution - Payment Methods Authenticated user should set additional payment method as default:
     Error: Unable to find an element with the text: Set as default. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
      at B (http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:16375)
      at http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:17493
      at http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:17219
      at http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:8687
      at MutationObserver.c (http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:16168)

  3) 576p resolution - Payment Methods Authenticated user should be able to delete payment method:
     Error: Unable to find an element with the text: Delete. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
      at B (http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:16375)
      at http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:17493
      at http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:8687
      at c (http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:16168)
      at http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:15990
      at new Promise (<anonymous>)
      at k (http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:15836)
      at http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:16333
      at Object.asyncWrapper (http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:15512)
      at A (http://localhost:4200/__cypress/tests?p=cypress/support/index.js-189:89:16299)

**Comment by bgambocjaviniar** [comment]
PR to maintenance: GH-6817
build 239 to 249
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/239/
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/249/

**Comment by bgambocjaviniar** [comment]
PR to develop: GH-6841
